---
- hosts: linux
  become: true

  tasks:
 
  - name: Update all installed packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    notify: Reboot servers
    when: ansible_os_family == "Redhat"


  - name: Update all installed package in Ubuntu
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    notify: Reboot servers
    when: ansible_os_family == "Debian"

  - name:  PermitRootLogin 
    ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        insertafter: "^#PermitRootLogin"

  - name: Reiniciar el servicio sshd ubuntu
    ansible.builtin.systemd:
      name: ssh
      state: restarted
    when: ansible_os_family == "Debian"

  - name: Reiniciar el servicio sshd centos
    ansible.builtin.systemd:
      name: sshd
      state: restarted
    when: ansible_os_family == "Redhat"

  handlers:

  - name: Reboot servers
    ansible.builtin.reboot:
    
