---
- hosts: ubuntu
  become: true

  tasks:
  - name: Install required packages for automount
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop:
      - autofs
      - nfs-common
      - python3

  - name: Add nfs.autods to auto.master.d
    ansible.builtin.copy:
      src: ../files/nfs.autofs
      dest: /etc/auto.master.d/nfs.autofs
      owner: root
      mode: '0644'

  - name: Add nfs mount map file
    ansible.builtin.copy:
      src: ../files/auto.nfs
      dest: /etc/auto.nfs
      owner: root
      mode: '0644'
    notify: Restart autofs

  - name: autofs service started
    ansible.builtin.systemd_service:
      name: autofs
      state: started
      enabled: true

 handlers:
  - name: restart autofs
    ansible.builtin.systemd_service:
      name: autofs
      state: restarted 

