---
- hosts: webservers
  become: true

  tasks:

  - name: Configuracion de webserver python
    ansible.builtin.copy:
      src: ../files/shared-http.service
      dest: /etc/systemd/system/shared-http.service
      owner: root
      mode: '0644'
    notify: Reload Systemd

  - name: Asegurar que el servicio esté habilitado y en ejecución
    ansible.builtin.systemd_service:
      name: shared-http
      enabled: yes
      state: started

  handlers:
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: yes
